import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex justify-between flex-col">
          <main>
            <Navbar
              navLinks={[
                { href: "/dashboard", name: "Dashboard" },
                { href: "/about", name: "About" },
                { href: "/contact", name: "Contact" },
                { href: "/blog", name: "Blog" },
              ]}
            ></Navbar>
            {children}
          </main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
