import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dahboard",
  description: "Generated by create next app",
};
export default function Dashboard() {
  return (
    <div>
      <h1>Ini Adalah dashboard</h1>
    </div>
  );
}
